Encryption: Encryption.o Substitution.o Trasposition.o
	gcc -o Encryption Encryption.o Substitution.o Trasposition.o

Encryption.o: Encryption.c
	gcc -c Encryption.c

Substitution.o: Substitution.c
	gcc -c Substitution.c

Transposition.o: Transposition.c
	gcc -c Transposition.c
